import {ArrowRight,BriefcaseBusiness,Building2,Check,Clock3,DollarSign,FileCheck2,ShieldCheck,Users} from "lucide-react";
import {PartnerShell} from "@/components/partner-shell";
const stats=[["OPEN JOBS","24","6 need review"],["ACTIVE LISTINGS","17","3 need attention"],["PEOPLE IN PIPELINE","184","31 moved this week"],["PLACEMENTS","14","8 hires · 6 leases"]];
export default function Home(){return <PartnerShell><div className="page">
 <section className="commandHero"><div><div className="eyebrow">PARTNER COMMAND</div><h1>Opportunity, operated.</h1><p>Run hiring, housing and placement from one FairPath workspace.</p></div><div className="heroActions"><button className="secondary square">Import opportunities</button><button className="primary square">Create opportunity</button></div></section>
 <section className="statStrip">{stats.map(([a,b,c])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</section>
 <section className="dashboardGrid">
  <div className="panel workbench"><div className="panelHead"><div><span className="kicker">WORKFORCE PIPELINE</span><h2>184 people moving toward work</h2></div><button className="textButton">Open workforce <ArrowRight size={14}/></button></div>
   <div className="stageRow">{[["Sourced",61],["Qualified",43],["Submitted",31],["Interview",22],["Offer",13],["Placed",8]].map(([x,n])=><div className="stage" key={String(x)}><span>{x}</span><b>{n}</b><div className="stageLine"><i style={{width:String(Math.min(Number(n)*1.6,100))+"%"}}/></div></div>)}</div>
   <div className="workRows"><div><span className="initial">DM</span><p><b>Darius M.</b><small>Warehouse · Forklift · Columbus</small></p><span className="tag">VERIFIED</span><strong>Interview</strong></div><div><span className="initial">AJ</span><p><b>Andre J.</b><small>Manufacturing · 2nd shift · Cleveland</small></p><span className="tag">BONDING READY</span><strong>Submitted</strong></div><div><span className="initial">TW</span><p><b>Tiana W.</b><small>Customer Support · Remote</small></p><span className="tag neutral">SCREENING</span><strong>Qualified</strong></div></div>
  </div>
  <aside className="panel pulse"><span className="kicker">TODAY</span><h2>Needs attention</h2><div className="attention"><div><FileCheck2/><p><b>12 applications</b><small>Waiting for review</small></p><strong>12</strong></div><div><Clock3/><p><b>4 interviews</b><small>Need confirmation</small></p><strong>4</strong></div><div><ShieldCheck/><p><b>3 screenings</b><small>Ready for decision</small></p><strong>3</strong></div></div><button className="fullButton">Open work queue <ArrowRight size={14}/></button></aside>
  <div className="panel"><div className="panelHead"><div><span className="kicker">HOUSING</span><h2>Property pipeline</h2></div><Building2 size={19}/></div><div className="housingNumbers"><div><strong>91</strong><span>Applications</span></div><div><strong>12</strong><span>Tours</span></div><div><strong>6</strong><span>Leases</span></div></div><div className="thinProgress"><i/></div><small className="caption">17 active listings across your workspace</small></div>
  <div className="panel"><div className="panelHead"><div><span className="kicker">STAFFING</span><h2>Placement desk</h2></div><BriefcaseBusiness size={19}/></div><div className="staffingMoney"><DollarSign/><strong>12,480</strong><span>projected monthly billings</span></div><div className="split"><span>8 active placements</span><span>3 clients</span></div><button className="textButton">Open placement desk <ArrowRight size={14}/></button></div>
  <div className="panel"><div className="panelHead"><div><span className="kicker">PROTECTION</span><h2>Reduce the risk of yes.</h2></div><ShieldCheck size={19}/></div><p className="bodyCopy">Verification, screening, bonding and housing protection belong in the decision workflow—not in separate systems.</p><div className="checkline"><Check size={14}/> 29 verified profiles ready</div><div className="checkline"><Check size={14}/> 11 protection actions available</div></div>
  <div className="panel"><div className="panelHead"><div><span className="kicker">OUTCOMES</span><h2>This month</h2></div><Users size={19}/></div><div className="outcome"><strong>14</strong><p>verified opportunities completed<small>8 hires · 6 leases</small></p></div><div className="outcomeLine"><i/></div></div>
 </section>
 </div></PartnerShell>}